In [106]:
# import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [107]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.4.26)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [108]:
import os
os.environ['KAGGLE_USERNAME']='asrapervaiz'
os.environ['KAGGLE_KEY'] = '46a2d40a05c1e0f41adf0e11fa8c2ea6'

In [109]:
!kaggle datasets download -d akshaygaikwad448/pizza-delivery-data-with-enhanced-features

Dataset URL: https://www.kaggle.com/datasets/akshaygaikwad448/pizza-delivery-data-with-enhanced-features
License(s): CC0-1.0
pizza-delivery-data-with-enhanced-features.zip: Skipping, found more recently modified local copy (use --force to force download)

In [110]:
!unzip pizza-delivery-data-with-enhanced-features.zip

Archive:  pizza-delivery-data-with-enhanced-features.zip
replace Enhanced_pizza_sell_data_2024-25.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [111]:
df = pd.read_excel('Enhanced_pizza_sell_data_2024-25.xlsx')

In [112]:
df

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
1,ORD002,Papa John's,"Los Angeles, CA",2024-02-14 20:00:00,2024-02-14 20:25:00,25,Large,Non-Veg,4,5.0,...,0.800000,February,Online,12.0,13.0,False,12,3,20,28.186275
2,ORD003,Little Caesars,"Chicago, IL",2024-03-21 12:15:00,2024-03-21 12:35:00,20,Small,Vegan,2,3.0,...,0.666667,March,Online,7.2,12.8,False,2,1,12,28.844221
3,ORD004,Pizza Hut,"Miami, FL",2024-04-10 19:45:00,2024-04-10 20:10:00,25,XL,Cheese Burst,5,4.5,...,1.111111,April,Offline,10.8,14.2,False,20,2,19,29.948454
4,ORD005,Marco's Pizza,"Dallas, TX",2024-05-05 13:00:00,2024-05-05 13:20:00,20,Medium,Non-Veg,3,2.0,...,1.500000,May,Online,4.8,15.2,False,6,3,13,30.286458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,ORD1001,Domino's,"Albuquerque, NM",2026-07-03 19:00:00,2026-07-03 19:30:00,30,Large,Sicilian,4,5.5,...,0.727273,July,Online,13.2,16.8,False,12,2,19,30.259434
1000,ORD1002,Pizza Hut,"Atlanta, GA",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,July,Online,9.6,20.4,False,4,1,20,29.948454
1001,ORD1003,Papa John's,"Omaha, NE",2026-07-05 18:30:00,2026-07-05 19:00:00,30,Medium,BBQ Chicken,3,5.0,...,0.600000,July,Online,12.0,18.0,False,6,2,18,28.186275
1002,ORD1004,Little Caesars,"Louisville, KY",2026-07-06 19:45:00,2026-07-06 20:15:00,30,XL,Cheese Burst,5,6.0,...,0.833333,July,Online,14.4,15.6,False,20,3,19,28.844221
1003,ORD1005,Marco's Pizza,"Milwaukee, WI",2026-07-07 20:00:00,2026-07-07 20:30:00,30,Medium,Margarita,3,4.5,...,0.666667,July,Online,10.8,19.2,False,6,2,20,30.286458

In [113]:
df.columns

Index(['Order ID', 'Restaurant Name', 'Location', 'Order Time',
       'Delivery Time', 'Delivery Duration (min)', 'Pizza Size', 'Pizza Type',
       'Toppings Count', 'Distance (km)', 'Traffic Level', 'Payment Method',
       'Is Peak Hour', 'Is Weekend', 'Delivery Efficiency (min/km)',
       'Topping Density', 'Order Month', 'Payment Category',
       'Estimated Duration (min)', 'Delay (min)', 'Is Delayed',
       'Pizza Complexity', 'Traffic Impact', 'Order Hour',
       'Restaurant Avg Time'],
      dtype='object')

In [114]:
df['Delivery Time'] = pd.to_datetime(df['Delivery Time'])

In [115]:
df

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
1,ORD002,Papa John's,"Los Angeles, CA",2024-02-14 20:00:00,2024-02-14 20:25:00,25,Large,Non-Veg,4,5.0,...,0.800000,February,Online,12.0,13.0,False,12,3,20,28.186275
2,ORD003,Little Caesars,"Chicago, IL",2024-03-21 12:15:00,2024-03-21 12:35:00,20,Small,Vegan,2,3.0,...,0.666667,March,Online,7.2,12.8,False,2,1,12,28.844221
3,ORD004,Pizza Hut,"Miami, FL",2024-04-10 19:45:00,2024-04-10 20:10:00,25,XL,Cheese Burst,5,4.5,...,1.111111,April,Offline,10.8,14.2,False,20,2,19,29.948454
4,ORD005,Marco's Pizza,"Dallas, TX",2024-05-05 13:00:00,2024-05-05 13:20:00,20,Medium,Non-Veg,3,2.0,...,1.500000,May,Online,4.8,15.2,False,6,3,13,30.286458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,ORD1001,Domino's,"Albuquerque, NM",2026-07-03 19:00:00,2026-07-03 19:30:00,30,Large,Sicilian,4,5.5,...,0.727273,July,Online,13.2,16.8,False,12,2,19,30.259434
1000,ORD1002,Pizza Hut,"Atlanta, GA",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,July,Online,9.6,20.4,False,4,1,20,29.948454
1001,ORD1003,Papa John's,"Omaha, NE",2026-07-05 18:30:00,2026-07-05 19:00:00,30,Medium,BBQ Chicken,3,5.0,...,0.600000,July,Online,12.0,18.0,False,6,2,18,28.186275
1002,ORD1004,Little Caesars,"Louisville, KY",2026-07-06 19:45:00,2026-07-06 20:15:00,30,XL,Cheese Burst,5,6.0,...,0.833333,July,Online,14.4,15.6,False,20,3,19,28.844221
1003,ORD1005,Marco's Pizza,"Milwaukee, WI",2026-07-07 20:00:00,2026-07-07 20:30:00,30,Medium,Margarita,3,4.5,...,0.666667,July,Online,10.8,19.2,False,6,2,20,30.286458

In [116]:
df.isnull().sum()

Order ID                        0
Restaurant Name                 0
Location                        0
Order Time                      0
Delivery Time                   0
Delivery Duration (min)         0
Pizza Size                      0
Pizza Type                      0
Toppings Count                  0
Distance (km)                   0
Traffic Level                   0
Payment Method                  0
Is Peak Hour                    0
Is Weekend                      0
Delivery Efficiency (min/km)    0
Topping Density                 0
Order Month                     0
Payment Category                0
Estimated Duration (min)        0
Delay (min)                     0
Is Delayed                      0
Pizza Complexity                0
Traffic Impact                  0
Order Hour                      0
Restaurant Avg Time             0
dtype: int64

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Order ID                      1004 non-null   object
 1   Restaurant Name               1004 non-null   object
 2   Location                      1004 non-null   object
 3   Order Time                    1004 non-null   datetime64[ns]
 4   Delivery Time                 1004 non-null   datetime64[ns]
 5   Delivery Duration (min)       1004 non-null   int64
 6   Pizza Size                    1004 non-null   object
 7   Pizza Type                    1004 non-null   object
 8   Toppings Count                1004 non-null   int64
 9   Distance (km)                 1004 non-null   float64
 10  Traffic Level                 1004 non-null   object
 11  Payment Method                1004 non-null   object
 12  Is Peak Hour                  1004 non-null   bool
 13  Is Weekend                    1004 non-null   bool
 14  Delivery Efficiency (min/km)  1004 non-null   float64
 15  Topping Density               1004 non-null   float64
 16  Order Month                   1004 non-null   object
 17  Payment Category              1004 non-null   object
 18  Estimated Duration (min)      1004 non-null   float64
 19  Delay (min)                   1004 non-null   float64
 20  Is Delayed                    1004 non-null   bool
 21  Pizza Complexity              1004 non-null   int64
 22  Traffic Impact                1004 non-null   int64
 23  Order Hour                    1004 non-null   int64
 24  Restaurant Avg Time           1004 non-null   float64
dtypes: bool(3), datetime64[ns](2), float64(6), int64(5), object(9)
memory usage: 175.6+ KB

In [118]:
df.drop(['Topping Density', 'Toppings Count', 'Delivery Efficiency (min/km)','Pizza Complexity'], axis=1, inplace = True)

In [119]:
df

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Distance (km),Traffic Level,...,Is Peak Hour,Is Weekend,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,2.5,Medium,...,True,False,January,Online,6.0,9.0,False,2,18,30.259434
1,ORD002,Papa John's,"Los Angeles, CA",2024-02-14 20:00:00,2024-02-14 20:25:00,25,Large,Non-Veg,5.0,High,...,True,False,February,Online,12.0,13.0,False,3,20,28.186275
2,ORD003,Little Caesars,"Chicago, IL",2024-03-21 12:15:00,2024-03-21 12:35:00,20,Small,Vegan,3.0,Low,...,False,False,March,Online,7.2,12.8,False,1,12,28.844221
3,ORD004,Pizza Hut,"Miami, FL",2024-04-10 19:45:00,2024-04-10 20:10:00,25,XL,Cheese Burst,4.5,Medium,...,True,False,April,Offline,10.8,14.2,False,2,19,29.948454
4,ORD005,Marco's Pizza,"Dallas, TX",2024-05-05 13:00:00,2024-05-05 13:20:00,20,Medium,Non-Veg,2.0,High,...,False,True,May,Online,4.8,15.2,False,3,13,30.286458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,ORD1001,Domino's,"Albuquerque, NM",2026-07-03 19:00:00,2026-07-03 19:30:00,30,Large,Sicilian,5.5,Medium,...,True,False,July,Online,13.2,16.8,False,2,19,30.259434
1000,ORD1002,Pizza Hut,"Atlanta, GA",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,4.0,Low,...,True,True,July,Online,9.6,20.4,False,1,20,29.948454
1001,ORD1003,Papa John's,"Omaha, NE",2026-07-05 18:30:00,2026-07-05 19:00:00,30,Medium,BBQ Chicken,5.0,Medium,...,True,True,July,Online,12.0,18.0,False,2,18,28.186275
1002,ORD1004,Little Caesars,"Louisville, KY",2026-07-06 19:45:00,2026-07-06 20:15:00,30,XL,Cheese Burst,6.0,High,...,True,False,July,Online,14.4,15.6,False,3,19,28.844221
1003,ORD1005,Marco's Pizza,"Milwaukee, WI",2026-07-07 20:00:00,2026-07-07 20:30:00,30,Medium,Margarita,4.5,Medium,...,True,False,July,Online,10.8,19.2,False,2,20,30.286458

In [120]:
df['Location'] = df['Location'].str.title().str.strip()
location_counts = df['Location'].value_counts()
df['Location_Order_Volume'] = df['Location'].map(location_counts)

In [121]:
df

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Distance (km),Traffic Level,...,Is Weekend,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Traffic Impact,Order Hour,Restaurant Avg Time,Location_Order_Volume
0,ORD001,Domino's,"New York, Ny",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,2.5,Medium,...,False,January,Online,6.0,9.0,False,2,18,30.259434,21
1,ORD002,Papa John's,"Los Angeles, Ca",2024-02-14 20:00:00,2024-02-14 20:25:00,25,Large,Non-Veg,5.0,High,...,False,February,Online,12.0,13.0,False,3,20,28.186275,42
2,ORD003,Little Caesars,"Chicago, Il",2024-03-21 12:15:00,2024-03-21 12:35:00,20,Small,Vegan,3.0,Low,...,False,March,Online,7.2,12.8,False,1,12,28.844221,45
3,ORD004,Pizza Hut,"Miami, Fl",2024-04-10 19:45:00,2024-04-10 20:10:00,25,XL,Cheese Burst,4.5,Medium,...,False,April,Offline,10.8,14.2,False,2,19,29.948454,49
4,ORD005,Marco's Pizza,"Dallas, Tx",2024-05-05 13:00:00,2024-05-05 13:20:00,20,Medium,Non-Veg,2.0,High,...,True,May,Online,4.8,15.2,False,3,13,30.286458,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,ORD1001,Domino's,"Albuquerque, Nm",2026-07-03 19:00:00,2026-07-03 19:30:00,30,Large,Sicilian,5.5,Medium,...,False,July,Online,13.2,16.8,False,2,19,30.259434,59
1000,ORD1002,Pizza Hut,"Atlanta, Ga",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,4.0,Low,...,True,July,Online,9.6,20.4,False,1,20,29.948454,78
1001,ORD1003,Papa John's,"Omaha, Ne",2026-07-05 18:30:00,2026-07-05 19:00:00,30,Medium,BBQ Chicken,5.0,Medium,...,True,July,Online,12.0,18.0,False,2,18,28.186275,68
1002,ORD1004,Little Caesars,"Louisville, Ky",2026-07-06 19:45:00,2026-07-06 20:15:00,30,XL,Cheese Burst,6.0,High,...,False,July,Online,14.4,15.6,False,3,19,28.844221,69
1003,ORD1005,Marco's Pizza,"Milwaukee, Wi",2026-07-07 20:00:00,2026-07-07 20:30:00,30,Medium,Margarita,4.5,Medium,...,False,July,Online,10.8,19.2,False,2,20,30.286458,71

In [123]:
df['Pizza Size'].value_counts()

Pizza Size
Medium    429
Large     240
XL        203
Small     132
Name: count, dtype: int64

In [124]:
df['Pizza Type'].value_counts()

Pizza Type
Non-Veg          216
Veg              202
Cheese Burst     188
Vegan            132
Sicilian          64
BBQ Chicken       54
Margarita         54
Gluten-Free       41
Thai Chicken      24
Stuffed Crust     21
Deep Dish          6
Thin Crust         2
Name: count, dtype: int64

In [125]:
# Define base prices per pizza type
base_prices = {
    'Non-Veg': 10,
    'Veg': 9,
    'Cheese Burst': 11,
    'Vegan': 10,
    'Sicilian': 12,
    'BBQ Chicken': 12,
    'Margarita': 8,
    'Gluten-Free': 11,
    'Thai Chicken': 13,
    'Stuffed Crust': 12,
    'Deep Dish': 14,
    'Thin Crust': 9
}

# Size price modifiers
size_modifier = {
    'Small': 0,
    'Medium': 2,
    'Large': 4,
    'XL': 6
}

# Generate full pricing dictionary
pricing = {}
for size in size_modifier:
    for pizza_type, base_price in base_prices.items():
        pricing[(size, pizza_type)] = base_price + size_modifier[size]

# Apply pricing to the DataFrame
df['Sales ($)'] = df.apply(lambda row: pricing.get((row['Pizza Size'], row['Pizza Type']), 0), axis=1)

In [127]:
Total_sales = df['Sales ($)'].sum()
Total_sales

np.int64(13367)

In [128]:
Total_orders = df.shape[0]
Total_orders

1004

In [129]:
Average_sale = df['Sales ($)'].mean()
Average_sale

np.float64(13.313745019920319)

In [133]:
Sales_by_Location = df.groupby('Location')['Sales ($)'].sum()
Sales_by_Location

In [132]:
Best_Selling_Pizza = df.groupby(['Pizza Type', 'Pizza Size'])['Sales ($)'].sum()
Best_Selling_Pizza

Pizza Type     Pizza Size
BBQ Chicken    Medium         756
Cheese Burst   Large          120
               XL            3060
Deep Dish      Large          108
Gluten-Free    Medium         533
Margarita      Medium         540
Non-Veg        Large         1092
               Medium        1632
               XL              32
Sicilian       Large          960
               Medium          42
               XL              18
Stuffed Crust  Large           16
               Medium          14
               XL             342
Thai Chicken   Large           51
               Medium         285
               Small           26
Thin Crust     Medium          22
Veg            Large         1092
               Medium        1298
Vegan          Medium          12
               Small         1300
               XL              16
Name: Sales ($), dtype: int64

In [135]:
Sales_by_day = df.groupby(df['Order Time'].dt.date)['Sales ($)'].sum()
Sales_by_day

Order Time
2024-01-05    11
2024-01-06    12
2024-01-07    13
2024-01-08    10
2024-01-09    17
              ..
2026-07-03    16
2026-07-04    11
2026-07-05    14
2026-07-06    17
2026-07-07    10
Name: Sales ($), Length: 847, dtype: int64

In [136]:
df['Order Time'] = pd.to_datetime(df['Order Time'])

# Extract hour/day/month
df['Order_Hour'] = df['Order Time'].dt.hour
df['Order_Day'] = df['Order Time'].dt.day_name()
df['Order_Month'] = df['Order Time'].dt.month_name()
df['Order_Date'] = df['Order Time'].dt.date

In [137]:
df['Distance Bucket'] = pd.cut(df['Distance (km)'],
                                bins=[0, 2, 5, 10, 20],
                                labels=['0–2 km', '2–5 km', '5–10 km', '10–20 km'])

# Save as CSV
df.to_csv("pizza_sales_analysis.csv", index=False)